mysite/blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from . import views

app_name = 'blog'

urlpatterns = [
    path('',
         cache_page(60 * 15)(views.PostListView.as_view()),
         name='post_list'),
    path('tag/<slug:category_slug>',
         views.PostListView.as_view(),
         name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<str:slug>',
         views.PostDetailView.as_view(),
         name='post_detail'),
    path('comment/add/<int:post_id>',
         views.CommentFormView.as_view(),
         name='submit_comment_form')
]

mysite/clients/urls.py
from django.urls import path
from .views import ClientFromView

app_name = 'clients'

urlpatterns = [
    path('', ClientFromView.as_view(), name="client_form"),
    path('<str:service>', ClientFromView.as_view(), name="client_form_params")
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.views.decorators.cache import cache_page

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('',
         cache_page(60 * 60)(TemplateView.as_view(template_name='main.html')),
         name='main'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('form/', include('clients.urls', namespace='clients')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mysite/templates/base.html
{% load i18n %}
{% load static %}
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
    <link rel="icon" type="image/x-icon" href="{% static 'images/favicon.ico' %}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.9.0/css/all.css">
    <script src='https://www.google.com/recaptcha/api.js?render={{ recaptcha_site_key }}'></script>
    <title>
        {% block title %}
        {% endblock title %}
    </title>
</head>
<body>
    {% include 'header.html' %}
    <main>
        {% block content %}{% endblock content %}
    </main>
    {% include 'footer.html' %}
    <script src="{% static 'js/script.js' %}"></script>
</body>
</html>

mysite/templates/footer.html
{% load i18n %}
<footer class="footer flex">
    <div class="container">
        <p class="footer-text">{% trans "Свяжитесь с нами" %}:</p>
        <ul>
            <li>
                <a href="https://m.facebook.com/Your.Estetist/?tsid=0.7593261866436525&source=result"><i class="fab fa-facebook"></i></a>
            </li>
            <li>
                <a href="https://instagram.com/your.estetist?utm_medium=copy_link"><i class="fab fa-instagram"></i></a>
               
            </li>
            <li>
                <a href="mailto:your.estetist@gmail.com"><i class="fa fa-envelope"></i></a>
            </li>
        </ul>
        <p class="footer-text copyright">&copy;2022 Estetist</p>
    </div>
</footer>

mysite/templates/header.html
{% load i18n %}
{% load static %}
<header id="navbar">
    <div class="container flex">
        <a href="{% url 'main' %}" class="logo"><h1>Estetist</h1></a>
        <nav>
            <ul id="navigation">
                <li><a href="{% url 'main' %}#about-us" class="navBtn">{% trans "О нас" %}</a></li>
                <li><a href="{% url 'blog:post_list'%}" class="navBtn">{% trans "Наш блог" %}</a></li>
                <li><a href="{% url 'main' %}#services" class="navBtn">{% trans "Услуги" %}</a></li>
                <li>
                    <a href="/uk">UA</a>
                </li>
                <li>
                    <a href="/ru">RU</a>
                </li>
            </ul>
        </nav>
    </div>
    {% include 'messages.html' %}
</header>

mysite/templates/main.html
{% extends 'base.html' %} {% load static %} {% load i18n %} {% block title %}
Estetist {% endblock title %} {% block content %}
<section class="container">
  <div class="estetist grid">
    <h1>{% trans "Индивидуальный подбор ухода за кожей лица" %}</h1>
    <p>{% trans "Выбирай косметику грамотно вместе с нашим специалистом" %}</p>
    <a href="{% url 'clients:client_form' %}"
      ><button>{% trans "Заказать подбор" %}</button></a
    >
    <img src="{% static 'images/img4.jpg' %}" alt="" />
  </div>
</section>
<section id="about-us" class="container section-2 grid">
  <div>
    <h2>
      Estetist.<br />
      {% trans "Здоровье - первый шаг к уверенности" %}
    </h2>
  </div>
  <div>
    <p>
      {% trans "Сегодня на рынке косметической продукции как никогда много
      разнообразных средств практически на все случаи жизни. Но, как часто
      бывает: чем больше вариантов - тем сложнее выбор. Мы предлагаем удобное и
      эффективное решение проблемы корректного подбора цельного комплекса
      косметического ухода в соответствии с индивидуальными потребностями
      клиента." %}
    </p>
  </div>
</section>
<section id="services" class="container section-3 grid">
  <a
    href="{% url 'clients:client_form_params' 'base' %}"
    class="link-prop-base"
  >
    <div>
      <p>{% trans "Пакет Базовый подбор" %}</p>
    </div>
    <div>
      <p>300 грн</p>
    </div>
    <div>
      <p>{% trans "Включает в себя" %}:<br />{% trans "Шаг 1 + Шаг 3" %}</p>
    </div>
  </a>
  <a
    href="{% url 'clients:client_form_params' 'plus' %}"
    class="link-prop-plus"
  >
    <div>
      <p>{% trans "Пакет Подбор Плюс" %}</p>
    </div>
    <div>
      <p>400 грн</p>
    </div>
    <div>
      <p>
        {% trans "Включает в себя" %}:<br />{% trans "Шаг 1 + Шаг 2 + Шаг 3" %}
      </p>
    </div>
  </a>
  <a
    href="{% url 'clients:client_form_params' 'full' %}"
    class="link-prop-full"
  >
    <div>
      <p>{% trans "Пакет Все включено" %}</p>
    </div>
    <div>
      <p>500 грн</p>
    </div>
    <div>
      <p>
        {% trans "Включает в себя полный перечень услуг" %}:<br />{% trans "Шаг1
        + Шаг 2 + Шаг 3 + Шаг 4" %}
      </p>
    </div>
  </a>
</section>
<section class="container section-4 grid">
  <div>
    <p>
      <span>{% trans "Шаг 1: Консультация" %}</span><br /><br />
      {% trans "Первое с чего стоит начать - определение типа кожи, обозначение
      конкретных проблем и поиск их первопричин. Вам будет предложено заполнить
      разработаную нашим специалистом форму, которая вдальнейшем будет
      проанализирована и станет основой для будущей консультации. Ответы на
      заданые вопросы позволят нашему косметоголу-эстетисту не только подобрать
      Вам правильный комплекс средств, но и понять Ваши привычки в уходе,
      которые, возможно, являются ошибочными, или же просто подкорректировать и
      улучшить некоторые этапы. Во время самой конультации у Вас будет
      возможность задать все накопившиеся вопросы, которые Вас интересуют. По
      итогу консультации Вы поймете логику каждого этапа ухода за кожей и какие
      именно компоненты из состава средств подходят именно Вам." %}
    </p>
  </div>
  <div>
    <p>
      <span>{% trans "Шаг 2 (опционально): разбор Вашей 'косметички'" %}</span>
      <br /><br />
      {% trans "Для составления полноценной картины лучше также проанализировать
      те продукты, которые Вы используете сейчас. Во-первых, это позволит нашему
      специалисту изучить составы используемых средств и дать заключение
      подходят ли они Вам и правильно ли Вы их используете. Зачастую, именно
      неверно подобранные компоненты ухода могут быть причиной ухудшения
      состояния кожи. Более того, после 'сортировки' вашей косметички, можно
      осуществить подбор на основе тех средств, которые Вам подходят и которые
      уже имеются, что будет значительно выгодней. " %}
    </p>
  </div>
  <div>
    <p>
      <span>{% trans "Шаг 3: Подбор уходового комплекса" %}</span><br /><br />
      {% trans "На основе полученой информации косметолог-эстетист подберет Вам
      оптимальный уход исходя из Ваших потребностей и бюджета. Кроме этого, Вам
      будет предоставлена подробная инструкция к премению данного комплекса, а
      также доплнительные полезные материалы." %}
    </p>
    <p>
      <span>{% trans "Шаг 4 (опционально): Готовый Beauty box" %}</span>
      <br /><br />
      {% trans "Для экономии Вашего времени предусмотрена услуга составления
      индивидуального Beauty box, который включает все рекомендуемые уходовые
      средства с доставкой в удобное для Вас время и место. Стоимость продукции
      соответствует официальной ценовой политике конкретного бренда. Также
      полный комплекс услуг, включая данное дополнение отлично подойдет в
      качестве подарка: полезно, удобно и эстетично." %}
    </p>
  </div>
</section>
<section class="container section-5 grid">
  <img src="{% static 'images/cosmetolog.jpg' %}" alt="cosmetolog" />
  <p>
    <span style="font-size: 40px">{% trans "Косметолог-эстетист" %}</span><br />
  </p>
  <p style="font-size: 20px">
    {% trans "Екатерина Никишина" %}<br /><br />
    {% trans "Подбор уходового комплекса проводит опытный и квалифицированный
    специалист, выпускник высшего учебного заведения Warszawska uczelnia
    medychna im. Tadeusza Kozluka, Варшава, Польша; Член Профессионального союза
    косметиков-эстетистов." %}
  </p>
</section>
<section class="section-6 flex">
  <p>{% trans "То, о чем Вам не расскажут консультанты в магазине" %}</p>
  <div class="arrow-7">
    <span></span>
    <span></span>
    <span></span>
  </div>
  <a href="{% url 'clients:client_form' %}">
    <button class="my-button">{% trans "Заказать подбор" %}</button>
  </a>
</section>
<section class="container">
  <div class="text-item">{% trans "Вы будете знать" %}:</div>
  <div class="section-7 grid">
    <div>
      <img src="{% static 'images/steps.png' %}" alt="" />
      <p class="text-center">
        {% trans "Какие обязательные этапы ухода для Вашего типа кожи" %}
      </p>
    </div>
    <div>
      <img src="{% static 'images/spices.png' %}" alt="" />
      <p class="text-center">
        {% trans "Какие ингредиенты являются наиболее эффективными для решения
        поставленных задач" %}
      </p>
    </div>
    <div>
      <img src="{% static 'images/calendar.png' %}" alt="" />
      <p class="text-center">
        {% trans "Через какой период времени нужно менять уходовый продукт и
        почему" %}
      </p>
    </div>
    <div>
      <img src="{% static 'images/cosmetics_3.png' %}" alt="" />
      <p class="text-center">
        {% trans "В чем разница между жесткими и мягкими средставами для
        умывания и какой тип подойдет именно Вам" %}
      </p>
    </div>
    <div>
      <img src="{% static 'images/cosmetics_1.png' %}" alt="" />
      <p class="text-center">
        {% trans "Крема Питающие VS Увлажняющие: Какой нужен Вашей коже?" %}
      </p>
    </div>
    <div>
      <img src="{% static 'images/cosmetics_2.png' %}" alt="" />
      <p>
        {% trans "Пиллинги, скрабы и маски: что, когда и как правильно
        применять" %}
      </p>
    </div>
  </div>
</section>
{% endblock content %}

mysite/templates/messages.html
{% if messages %}
    {% for message in messages %}
        <div {% if message.tags %} class="{{ message.tags }}" {% endif %}>
            <span class="closebtn" onclick="this.parentElement.style.display='none';">&times;</span> 
            {{ message|safe }} 
        </div>
    {% endfor %}
{% endif %}  

mysite/templates/sidebar.html
{% load blog_tags %} 
{% load i18n %}
{% load cache %}
{% cache 600 sidebar %}
<div class="side-bar">
  <div class="form-wrapper search">{% search %}</div>
  <h2>{% trans "Последние публикации" %}:</h2>
  {% show_latest_posts 3 as latest_posts %}
  <ul>
    {% for post in latest_posts %}
    <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
    <hr />
    {% endfor %}
  </ul>
  <h2>{% trans "Популярные" %}:</h2>
  {% get_most_commented_posts as top%}
  <ul>
    {% for post in top %}
    <li><a href="{{ post.get_absolute_url }}">{{ post.title }}</a></li>
    <hr />
    {% endfor %}
  </ul>
  <h2>{% trans "Категории" %}:</h2>
  {% categories as categories%}
  <ul>
    {% for category in categories %}
    <li>
      <a href="{{ category.get_absolute_url }}">{{ category.name|capfirst }}</a>
    </li>
    <hr />
    {% endfor %}
  </ul>
</div>
{% endcache %}