mysite/blog/urls.py
from django.urls import path
from django.views.decorators.cache import cache_page
from . import views

app_name = 'blog'

urlpatterns = [
    path('',
         cache_page(60 * 15)(views.PostListView.as_view()),
         name='post_list'),
    path('tag/<slug:category_slug>',
         views.PostListView.as_view(),
         name='post_list_by_tag'),
    path('<int:year>/<int:month>/<int:day>/<str:slug>',
         views.PostDetailView.as_view(),
         name='post_detail'),
    path('comment/add/<int:post_id>',
         views.CommentFormView.as_view(),
         name='submit_comment_form')
]

mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView
from django.conf import settings
from django.conf.urls.static import static
from django.conf.urls.i18n import i18n_patterns
from django.views.decorators.cache import cache_page

urlpatterns = i18n_patterns(
    path('admin/', admin.site.urls),
    path('ckeditor/', include('ckeditor_uploader.urls')),
    path('',
         cache_page(60 * 60)(TemplateView.as_view(template_name='main.html')),
         name='main'),
    path('blog/', include('blog.urls', namespace='blog')),
    path('form/', include('clients.urls', namespace='clients')),
)

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL,
                          document_root=settings.MEDIA_ROOT)

mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.utils.translation import gettext_lazy as _


class Category(models.Model):
    name = models.CharField(_('Название категории'), max_length=120)
    slug = models.SlugField(_("URL категории"))

    class Meta:
        verbose_name = _('Категория')
        verbose_name_plural = _('Категории')

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse('blog:post_list_by_tag', args=[self.slug])


class Post(models.Model):

    STATUS_CHOICES = (
        (_('черновик'), _('Чeрновик')),
        (_('опубликовано'), _('Опубликовано')),
    )

    title = models.CharField(_('Заголовок'), max_length=250)
    image = models.ImageField(_('Изображение'), upload_to='post_images/')
    slug = models.SlugField('URL', max_length=250, unique_for_date='publish')
    body = models.TextField(_("Текст поста"))
    publish = models.DateTimeField(_('Дата публикации'), default=timezone.now)
    created = models.DateTimeField(_('Дата создания'), auto_now_add=True)
    updated = models.DateTimeField(_('Дата последнего редактирования'),
                                   auto_now=True)
    status = models.CharField(_('Статус поста'),
                              max_length=12,
                              choices=STATUS_CHOICES,
                              default=_('черновик'))
    category = models.ManyToManyField(Category, related_name='posts')

    class Meta:
        ordering = ('-publish', )
        verbose_name = _('Пост')
        verbose_name_plural = _('Посты')

    def __str__(self):
        return self.title

    def get_absolute_url(self):
        return reverse('blog:post_detail',
                       args=[
                           self.publish.year, self.publish.month,
                           self.publish.day, self.slug
                       ])


class Comment(models.Model):

    post = models.ForeignKey(Post,
                             verbose_name=_('Пост'),
                             on_delete=models.CASCADE,
                             related_name='comments')
    name = models.CharField(_('Имя'), max_length=80)
    email = models.EmailField()
    body = models.TextField(_('Текст комментария'))
    created = models.DateTimeField(_('Дата создания'), auto_now_add=True)
    updated = models.DateTimeField(_('Дата последнего редактирования'),
                                   auto_now=True)
    active = models.BooleanField(_('Активный'), default=True)

    class Meta:
        ordering = ('created', )
        verbose_name = _('Комментарий')
        verbose_name_plural = _('Комментарии')

    def __str__(self):
        return f'Комментарий сделанный {self.name} к публикации {self.post}'

mysite/blog/forms.py
from django import forms
from .models import Comment
from django.utils.translation import gettext_lazy as _


class CommentForm(forms.ModelForm):

    class Meta:
        model = Comment
        fields = (
            'name',
            'email',
            'body',
        )
        widgets = {
            'name': forms.TextInput,
            'email': forms.EmailInput,
            'body': forms.Textarea,
        }

        labels = {'body': _('Ваш комментарий')}


class SearchForm(forms.Form):
    query = forms.CharField(label='')

    class Meta:
        widgets = {
            'query': forms.TextInput,
        }

mysite/blog/views.py
from .models import Category, Post, Comment
from .forms import CommentForm
from django.db.models import Q, Prefetch
from django.contrib.postgres.search import SearchVector, SearchQuery, SearchRank
from django.views.generic import ListView, DetailView
from django.views.generic.edit import CreateView


class PostListView(ListView):
    queryset = Post.objects.filter(
        Q(status='опубликовано') | Q(status='опубліковано'))
    paginate_by = 6
    template_name = 'blog/blog_list.html'
    context_object_name = 'posts'
    category = None
    query = None

    def get_queryset(self):
        queryset = super().get_queryset()
        self.query = self.request.GET.get('query', None)
        category_slug = self.kwargs.get('category_slug', None)
        if category_slug:
            self.category = Category.objects.get(slug=category_slug)
        if self.query:
            language = self.request.LANGUAGE_CODE
            search_vector = SearchVector(f'title_{language}',
                                         weight='A') + SearchVector(
                                             f'body_{language}', weight='B')
            search_query = SearchQuery(self.query)
            queryset = queryset.annotate(
                rank=SearchRank(search_vector, search_query)).filter(
                    rank__gte=0.1).order_by('-rank')
        if self.category:
            queryset = queryset.filter(category__slug__in=[self.category.slug])
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["category"] = self.category
        context['query'] = self.query
        return context


class PostDetailView(DetailView):
    queryset = Post.objects.filter(
        Q(status='опубликовано') | Q(status='опубліковано'))
    context_object_name = 'post'
    template_name = 'blog/blog_detail.html'

    def get_queryset(self):
        queryset = super().get_queryset()
        queryset = queryset.prefetch_related(
            Prefetch('comments', queryset=Comment.objects.filter(active=True)))
        return queryset

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context['form'] = CommentForm
        return context


class CommentFormView(CreateView):
    form_class = CommentForm

    def form_valid(self, form):
        self.post = Post.objects.get(id=self.kwargs.get('post_id'))
        form.instance.post = self.post
        self.request.session[f'{self.post.slug}'] = True
        return super().form_valid(form)

    def get_success_url(self):
        return self.post.get_absolute_url()

mysite/templates/blog/blog_detail.html
{% extends 'base.html' %} 
{% load i18n %}
{% load social_share %} 
{% block title%} 
{{ post.title }} 
{% endblock title %} 
{% block content %}
<div>
  <div class="blog-post-title flex">
    <h1>{{ post.title }}</h1>
    <span class="pub-date">{% trans "Опубликовано" %}: {{ post.publish}}</span>
    <ul>
      <li>
        {% post_to_whatsapp object_or_url '<i class="fab fa-whatsapp"></i>' %}
      </li>
      <li>
        {% post_to_telegram '{{ post.title}}: ' object_or_url '<i class="fab fa-telegram"></i>' %}
      </li>
      <li>
        {% post_to_facebook object_or_url '<i class="fab fa-facebook"></i>' %}
      </li>
    </ul>
  </div>
  <div class="blog-post grid">
    <div class="post-detail">
      <img src="{{ post.image.url }}" alt="{{ post.title }}" />
      <p>{{ post.body|safe }}</p>
    </div>
    {% with post.slug as key%}
    {% if key not in request.session %}
    <div class="form-wrapper">
      <h3>{% trans "Оставьте комментарий:" %}</h3>
      <form method="post" action="{% url "blog:submit_comment_form" post.id %}" class="estetist-form">
        {% csrf_token %} 
        {{ form.as_ul }} 
        <input type="submit" value="{% trans "Оставить комментарий" %}" class="row-button">
      </form>
    </div>
    {% endif %}
    {% endwith %}
    <div class="comments flex">
      <h3>{% trans "Комментарии" %}:</h3>
      {% with post.comments.all as comments %} 
      {% for comment in comments %}
      <div class="comment">
        <span>{{ comment.name }} | {{ comment.created }}</span>
        <p>{{ comment.body }}</p>
      </div>
      {% empty %}
      <p>{% trans "К этой публикации еще нет комментариев" %}.</p>
      {% endfor %} {% endwith %}
    </div>
    <div class="similar flex">
      <h3>{% trans "Похожие публикации" %}:</h3>
      {% for similar_post in similar_posts %}
      <a href="{{ similar_post.get_absolute_url }}" class="similar-link">{{ similar_post.title }}</a
      >
      {% empty %}
      <p>{% trans "Извините, но пока нет похожих публикаций" %}.</p>
      {% endfor %}
    </div>
    {% include 'sidebar.html' %}
  </div>
</div>
{% endblock content %}

mysite/templates/blog/blog_list.html
{% extends 'base.html' %}
{% load i18n %}
{% block title %}Наш Блог{% endblock title %}
{% block content %}
<div class="listview">
    <div class="blog-title flex">
        <h1>Estetist`s blog</h1>
        {% trans "Делимся опытом, делимся идеями, делимся новостями" %}
        {% if category %}
        <p>{% trans "Публикации отсортированные за категорией" %}: {{ category.name }}</p>
        {% endif %}
        {% if query %}
        <p>{% trans "Публикации которые содержат поисковый запрос" %}: "{{ query }}".</p>
        {% endif %}
    </div>
    <div class="blog-list grid">
        {% for post in posts %}
            <div class="post">
                <a href="{{ post.get_absolute_url }}">
                    <div class="post-image">
                        <img src="{{ post.image.url }}" alt="{{ post.title }}">
                    </div>
                    <h2>{{ post.title }}</h2>
                    <p>{{ post.body|safe|truncatewords:30 }}</p>
                    <span class="date">{{ post.publish}}</span>
                </a>
            </div>
        {% empty %}
            {% if query %}
                <p>{% trans "За вашим поисковым запросом не найдено ничего" %}.</p>
            {% endif %}
        {% endfor %}
        {% include 'sidebar.html' %}
    </div>
    <div class="flex">
        <div class="pagination">
            <span class="step-links">
                {% if page_obj.has_previous %}
                    <a href="?page=1"><i class="fas fa-angle-double-left"></i>
                    </a>
                    <a href="?page={{ page_obj.previous_page_number }}"><i class="fas fa-angle-left"></i></a>
                {% endif %}
                <span class="current">
                    {% trans "Страница" %} {{ page_obj.number }} {% trans "из" %} {{ page_obj.paginator.num_pages }}.
                </span>
                {% if page_obj.has_next %}
                    <a href="?page={{ page_obj.next_page_number }}"><i class="fas fa-angle-right"></i></a>
                    <a href="?page={{ page_obj.paginator.num_pages }}"><i class="fas fa-angle-double-right"></i>
                    </a>
                {% endif %}
            </span>
        </div>
    </div>
</div>
{% endblock content %}
        
    

mysite/templates/blog/search.html
{% load i18n %}
<h2>{% trans "Поиск по блогу" %}</h2>
<form action="{% url 'blog:post_list' %}" method="get">
  {{ search_form.as_ul }}
  <input type="submit" value="Поиск" class="row-button" />
</form>